export const theme = {
    light: {
        primaryColor: '#f15a29',
        primaryBgColor: '#f8f5f2',
        primaryBgColorPage: '#fff',
        primaryBgColorDiv: '#c4c4c4',
        textColor: '#000',
        inputColor: '#000',
        focusColor: '#484848',
        hoverColor: '#BDD3E9',
        messagesScreenSidebarColor: '#324b51',
        messagesScreenSidebarTextColor: '#f1f1e6',
        searchContactsBgColor: '#72898f',
        searchContactsTextColor: '#f0f0ef',
    },
    dark: {
        primaryColor: '#f15a29',
        primaryBgColor: '#2f4858',
        primaryBgColorPage: '#374955',
        primaryBgColorDiv: '#9baebc',
        textColor: '#fff',
        inputColor: '#fff',
        focusColor: '#acacac',
        hoverColor: '#BDD3E9',
        messagesScreenSidebarColor: '#324b51',
        messagesScreenSidebarTextColor: '#f1f1e6',
        searchContactsBgColor: '#72898f',
        searchContactsTextColor: '#f0f0ef',
    },
};
